### ISSUE TITLE
How do I install GerritPlugin in GitExtensions v3.4?

### ISSUE THREAD

**Issue by OvidiuCaba** [gitextensions/GitExtensions.GerritPlugin#13]
GerritPlugin is no longer part of the installation package of GitExtensions. I tried to use PluginManager, but GerritPlugin is not published or, if it is, I cannot find it. So, how do I install the GerritPlugin on a clean instance of GitExtensions v3.4?

I tried to copy Gerrit.dll from a colleague in my GE\Plugins folder, but this doesn't fix the issue. What I am missing here?

Thank you in advance,
Ovidiu Caba

**Comment by pmiossec** [comment]
>I tried to use PluginManager, but GerritPlugin is not published or, if it is, I cannot find it.

It is published. I can find it.

![image](https://user-images.githubusercontent.com/460196/84764392-f01fe500-afcd-11ea-9741-0071071e4f1f.png)

Did you launch the Plugin manager from the "plugins" menu?

**Comment by OvidiuCaba** [comment]
> Did you launch the Plugin manager from the "plugins" menu?

No, because I was not able to install it. I have an error on installation and when I run it from GitExtensions, it crashes.

I run it from command line:

`PackageManager.UI.exe --path "C:\Program Files (x86)\GitExtensions\Plugins"`

**Comment by RussKie** [comment]
> No, because I was not able to install it. I have an error on installation and when I run it from GitExtensions, it crashes.

I suppose you should have started with this. What kind of error do you get?

**Comment by RussKie** [comment]
I just ran it, no issues:
![image](https://user-images.githubusercontent.com/4403806/84765246-4f074d80-b012-11ea-9247-46f2ee32068c.png)

**Comment by OvidiuCaba** [comment]
![image](https://user-images.githubusercontent.com/6516996/84765203-91f7ff80-afd7-11ea-9d97-25c01b24ce90.png)

`6/16/2020 1:44:42 PM root.Startup.Package(INFO)

  GET https://www.myget.org/F/neptuo-gitextensions/api/v2/Packages(Id='GitExtensions.PluginManager',Version='0.9.0')

6/16/2020 1:44:43 PM root.Startup.Package(INFO)

  OK https://www.myget.org/F/neptuo-gitextensions/api/v2/Packages(Id='GitExtensions.PluginManager',Version='0.9.0') 347ms

6/16/2020 1:44:43 PM root.Startup.Package(INFO)

  GET https://www.myget.org/F/neptuo-gitextensions/api/v2/package/GitExtensions.PluginManager/0.9.0

6/16/2020 1:44:43 PM root.Startup.Package(INFO)

  OK https://www.myget.org/F/neptuo-gitextensions/api/v2/package/GitExtensions.PluginManager/0.9.0 255ms

6/16/2020 1:44:43 PM root.Startup.Package(DEBUG)

Extracting file 'C:\Program Files (x86)\GitExtensions\Plugins\GitExtensions.PluginManager\GitExtensions.PluginManager.dll'.

6/16/2020 1:44:43 PM root.Exception(FATAL)

PackageManager.Models.PackageFileExtractionException: Error deleting file from 'C:\Program Files (x86)\GitExtensions\Plugins\GitExtensions.PluginManager\lib\GitExtensions.PluginManager.dll'. ---> System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\GitExtensions\Plugins\GitExtensions.PluginManager\GitExtensions.PluginManager.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at PackageManager.Models.NuGetPackageContent.<>c__DisplayClass8_1.<ExtractToAsync>g__ExtractFile|1(String sourceFile, String targetPath, Stream sourceContent)
   --- End of inner exception stack trace ---
   at PackageManager.Models.NuGetPackageContent.<>c__DisplayClass8_1.<ExtractToAsync>g__ExtractFile|1(String sourceFile, String targetPath, Stream sourceContent)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at PackageManager.Models.NuGetPackageContent.<>c__DisplayClass8_0.<<ExtractToAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PackageManager.ViewModels.Commands.InstallCommand.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neptuo.Observables.Commands.AsyncCommand`1.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neptuo.Observables.Commands.AsyncCommand`1.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

`

**Comment by RussKie** [comment]
> when I try to install PluginManager

The Plugin Manager is installed as part of Git Extensions
![image](https://user-images.githubusercontent.com/4403806/84765542-b7562f00-b012-11ea-9f11-88a7a633f9b4.png)

**Comment by OvidiuCaba** [comment]
In uninstalled Git Extensions and now I try to reinstall it. Here is the list of the plugins that are going to be installed:

![image](https://user-images.githubusercontent.com/6516996/84766008-c7e9b380-afd8-11ea-8c43-5b985e71861c.png)

![image](https://user-images.githubusercontent.com/6516996/84766033-d33cdf00-afd8-11ea-8ed7-ee65a3d3206f.png)

![image](https://user-images.githubusercontent.com/6516996/84766063-ddf77400-afd8-11ea-842a-e82ee786c384.png)

I don't see the Plugin Manager in this list. I install v3.4.1 (the last version).

**Comment by RussKie** [comment]
We don't list it because we don't give an option not to install the Plugin
Manager as it is an integral part of the bundle.

**Comment by OvidiuCaba** [comment]
Perhaps it would be a good idea to update the documentation? I was not able to find any information regarding how to install this plugin no matter what keywords or links I tried.

**Comment by RussKie** [comment]
Fair point. Which documentation did you look at?

**Comment by OvidiuCaba** [comment]
Among others, I think this link is relevant: https://git-extensions-documentation.readthedocs.io/en/latest/plugins.html

**Comment by RussKie** [comment]
@mast-eu do you think you could action this when you get a chance? Thank you

**Comment by mast-eu** [comment]
> @mast-eu do you think you could action this when you get a chance?

Yes, will do.

**Comment by pmiossec** [comment]
A thing I already thought about previously and that I think could improve
the UX and that we could do as part of 'fixing' this bug is to give the
plugin manager a special treatment to make it more visible (and not lost in
the plugins list).

And so, put it:

* either on top of the menu with separator
* or at the bottom next to 'Settings...'

**Comment by pmiossec** [comment]
What do you think?

![image](https://user-images.githubusercontent.com/460196/84777647-27988c80-afe2-11ea-8815-ce89dad6fa51.png)

**Comment by RussKie** [comment]
Maybe?...

**Comment by OvidiuCaba** [comment]
> A thing I already thought about previously and that I think could improve the UX and that we could do as part of 'fixing' this bug is to give the plugin manager a special treatment to make it more visible (and not lost in the plugins list). And so, put it: * either on top of the menu with separator * or at the bottom next to 'Settings...'

Actually this is the very good idea as the moment I realized I do not have the Gerrit plugin, I looked for a way to install it within the Settings window. I hoped that I would find something there that would help me to install the Gerrit plugin. [the menu separator is also a good idea]

**Comment by mast-eu** [comment]
I like @pmiossec `s idea to put the Plugin Manager at the bottom of the plugins menu, together with Plugin Settings. It's not a "normal" plugin, thus a special location for its menu item makes sense.
