### ISSUE TITLE
Error message on Dashboard

### ISSUE THREAD

**Issue by VStark** [gitextensions/GitExtensions.GerritPlugin#63]
### Environment

- Gerrit plugin version: I don't know
- Git Extensions version: 4.0.1.15887
- GIT version: 2.39.0
- OS version: windows 10
- .NET version: 6.0.12

### Issue description

After launch of the Git Extensions application the error message is shown on dashboard (for some reason it pops up twice)
![image](https://user-images.githubusercontent.com/21239324/211756250-be97f75f-34c5-4cf8-9280-0f45fe71a9e4.png)
[Reference: ](https://github.com/gitextensions/gitextensions/issues/10448)

### Steps to reproduce

Open application.
Clean installation.

### Expected behavior

There won't be any error

### Actual behavior

Stack trace:
```
File name:   C:\Program Files\Git\bin\git.exe
Arguments:   rev-parse --git-path "hooks"
Working dir: 
Process ID:  21356
Started at:  2023-01-10T09:45:48.9054378+01:00
UI Thread?:  True
Duration:    47,644 ms
Exit code:   GitExtUtils.ExternalOperationException: fatal: not a git repository (or any of the parent directories): .git
 ---> System.Exception: fatal: not a git repository (or any of the parent directories): .git
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResolveGitInternalPath(String relativePath)
   at GitExtensions.GerritPlugin.GerritPlugin.GetCommitMessageHookPath(IGitModule gitModule)
   at GitExtensions.GerritPlugin.GerritPlugin.HasValidCommitMsgHook(IGitModule gitModule, Boolean force)
   at GitExtensions.GerritPlugin.GerritPlugin.UpdateGerritMenuItems(Object sender, GitUIEventArgs e)
   at GitUI.GitUICommands.InvokeEvent(IWin32Window ownerForm, EventHandler`1 gitUIEventHandler)
Call stack:  not captured
```

### Did this work in previous version of Gerrit plugin?

Yes, When I was using version 3.

**Comment by lekhmanrus** [comment]
Hi @VStark,
I can't reproduce your error, could you please tell me the Gerrit plugin version? you can find it in the GE Plugin Manager.
Thanks!

**Comment by VStark** [comment]
![image](https://user-images.githubusercontent.com/21239324/212665115-88d03072-0fbb-4513-a410-8b652ea8fe7f.png)

**Comment by lekhmanrus** [comment]
I still can't reproduce that. Could you please try GerritPlugin v2.0.4 ?
