### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.String GitUIPluginInterfaces.IGitModule.GetSelectedBranch()' with GE 4.2

### ISSUE THREAD

**Issue by dfev77** [gitextensions/GitExtensions.GerritPlugin#80]
### Environment

- Gerrit plugin version: 2.0.6.196
- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: True
```
System.MissingMethodException: Method not found: 'System.String GitUIPluginInterfaces.IGitModule.GetSelectedBranch()'.
   at GitExtensions.GerritPlugin.FormGerritPublish.GetBranchName(String targetBranch)
   at GitExtensions.GerritPlugin.FormGerritPublish.FormGerritPublishLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at GitUI.GitExtensionsForm.OnLoad(EventArgs e) in C:\projects\gitextensions\GitUI\GitExtensionsForm.cs:line 67
   at GitExtensions.GerritPlugin.FormGerritBase.OnLoad(EventArgs e)
   at GitExtensions.GerritPlugin.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m) in C:\projects\gitextensions\ResourceManager\GitExtensionsFormBase.cs:line 107
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Issue description

Cannot publish changeset with GE 4.2
PS: setting the "new" config value "Target branch selection" to ".gitreview file" does not help, same error is encountered

### Steps to reproduce

push the publish button

### Expected behavior

change is published to Gerrit

### Actual behavior

error

**Comment by lekhmanrus** [comment]
Fixed in #82.
Thanks @dfev77!
